### ISSUE TITLE
Thunderdome: Prove the idea

### ISSUE THREAD

**Issue by iand** [protocol/prodeng#16]
For the first pass `dealgood` will read from stdin a JSONL description of the request pattern, we will use SSH, `tail -F`  and some python/Go stream rewriting to give us the requests to replay.

`dealgood` writes status to console every few seconds, for each target:

- number of requests
- counts per returncode
- TTFB percentiles per return code
- response time percentiles per returncode
- aggregate TTFB/response time for the target

`dealgood` should also write a log of every request and detailed information about the reponses

Project overview is on [Notion](https://www.notion.so/pl-strflt/Project-2-Thunderdome-9329254f11a441d586de9146f51aeedc)

## Tasks

- [x] https://github.com/ipfs-shipyard/thunderdome/issues/7
- [x] https://github.com/ipfs-shipyard/thunderdome/issues/23
- [x] https://github.com/protocol/prodeng/issues/21
