### ISSUE TITLE
Thunderdome: Run Initial Kubo Experiments

### ISSUE THREAD

**Issue by iand** [protocol/prodeng#24]
## What Is It?

Create and run some initial experiments in Thunderdome against live traffic.

## Deliverables

 - Docker images and Thunderdome configuration for each experiment. 
 - A Grafana dashboard and a short analysis of key results from running each experiment.

## Why Are We Doing It?

Running these initial experiments will demonstrate that the basic Thunderdome infrastructure works and can produce interesting results. Some of the experiments have current practical value:
 - Comparing the current release candidate of Kubo against the previous version could detect possible performance regressions or improvements. 
 - Comparing different values of the provider delay setting can inform the decision on what will be the best value to use by default in Kubo.
 - Comparing different tracing levels can help us understand the trade off between performance and utility when enabling tracing in production

## Notes

Experiments should run for a significant time such as 12 or 24 hours.

## Tasks

 - [x] https://github.com/ipfs-shipyard/thunderdome/issues/3
 - [ ] https://github.com/ipfs-shipyard/thunderdome/issues/5
 - [x] https://github.com/ipfs-shipyard/thunderdome/issues/9
 - [x] https://github.com/ipfs-shipyard/thunderdome/issues/11
 - [x] https://github.com/ipfs-shipyard/thunderdome/issues/33

**Comment by iand** [comment]
See https://www.notion.so/pl-strflt/Thunderdome-Update-7-Sep-2022-9679a762b59f423b87bc2258a9c7e1ec for summary of initial experiment runs
