### ISSUE TITLE
Thunderdome: Run Further Kubo Experiments

### ISSUE THREAD

**Issue by iand** [protocol/prodeng#25]
## What Is It?

Define and run experiments submitted by users against live traffic.

## Deliverables

 - Docker images and Thunderdome configuration for each experiment.
 - A Grafana dashboard and a short analysis of key results from running each experiment.

## Why Are We Doing It?

Since demoing Thunderdome's Grafana integration we have received a lot of interest from the IPFS/LibP2P stewards incuding ideas for new experiments. Running these and providing data on the outcomes will help inform design decisions by stewards.

## Tasks

- [ ] https://github.com/ipfs-shipyard/thunderdome/issues/47
- [ ] https://github.com/ipfs-shipyard/thunderdome/issues/45
- [ ] Share summary of experiments run and outcomes
